name: Magnet
version: ${project.version}
main: jericraft.chalwk.magnet
api-version: 1.16
authors: [Chalwk]
description: Items will be drawn towards the player
website: jericraft.enjin.com
commands:
  magnet:
    description: Items will be drawn towards you
    usage: /<command> on|off
permissions:
  magnet.use:
    description: Access to magnet on|off command
    default: op