##################################################
# Dynamic Ping Kicker config.yml file
# Copyright, 2020, Jericho Crosby <jericho.crosby227@gmail.com>
######################################################################################

# Players will be kicked after this many warnings:
max-warnings: 5

# Checks done every check-interval seconds:
check-interval: 25

# If the players ping has been stable for this amount of time, their warnings will be reset.
grace-period: 30

# Players/Groups with this permission nodes will be ignored
ignore-permission: "dynamicpingkicker.ignore"

# Ping Limits are based on current player count: (min players|max players|limit)
limits:
  # Start ping kicking if there are 1 to 4 players (if 750+ ping)
  - {min-players: 1, max-players: 4, ping-limit: 750}
  # Start ping kicking if there are 5 to 8 players (if 450+ ping)
  - {min-players: 5, max-players: 8, ping-limit: 450}
  # Start ping kicking if there are 9 to 12 players (if 375+ ping)
  - {min-players: 9, max-players: 12, ping-limit: 375}
  # Start ping kicking if there are 13 to 16 players (if 200+ ping)
  - {min-players: 13, max-players: 16, ping-limit: 200}

messages:
  warn:
    - '&7--- [ &4HIGH PING WARNING &7] ---'
    - '&eYour ping is too high! Limit: %limit% (ms) Your Ping: %ping% (ms)'
    - '&ePlease try to lower it if possible'
  kick:
    - '&7--- &4PING KICK &7---'
    - '&a%name% &ewas kicked for high ping. Limit: %limit% (ms) Their Ping: %ping% (ms)'
