# Expressions config.yml
# Copyright 2020, Jericho Crosby, <jericho.crosby227@gmail.com>

# Plugin supports chat colors

settings:
  anger:
    trigger: "!anger"
    messages:
      - "FOR GOODNESS SAKES"
      - "OUH C'MON!"
      - "ARE YOU SERIOUS!?"
      - "WHAT A LOAD OF BOLLOCKS"
      - "OH HELL NAH!"
      - "GRRRRRRR!!"
      - "*FLARES NOSTRILS*"
      - "*SCREAMS AT TOP OF LUNGS*"
      - "BOLLOCKS"
  cuss:
    trigger: "!cuss"
    messages:
      - "Shnookerdookies!"
      - "Fudge nuggets!"
      - "Cheese and rice!"
      - "Sugar!"
      - "Poo!"
      - "Snickerdoodle!"
      - "Banana shenanigans!"
      - "Six and two is eight!"
      - "God bless it!"
      - "Barbara Streisand!"
      - "Fiddlesticks!"
      - "Jiminy Crickets!"
      - "Son of a gun!"
      - "Egad!"
      - "Great Scott!"
      - "Caesar's ghost!"
      - "Merlin's beard!"
      - "Merlin's pants!"
      - "Shucks!"
      - "Darn!"
      - "Dagnabbit!"
      - "Dang rabbit!"
      - "Dadgummit!"
      - "Jumpin' Jiminy!"
  taunt:
    trigger: "!taunt"
    messages:
      - "Ees too bad you got manure for brains!!"
      - "Hell's full a' retired Gamers, And it's time you join em!"
      - "Hell! My horse pisses straighter than you shoot!!"
      - "Can't you do better than that! I've seen worms move faster!"
      - "Not good enough!"
      - "Hell - I can already smell your rotting corpse."
      - "Today is a good day to die, Mr!"
      - "I'm going to send ya to an early grave"
      - "Had enough yet?!"
      - "Damn you and the horse you rode in on!"
      - "Time to fit you for a coffin!"
      - "Your life ends in the wasteland..."
      - "Sell your PC. Just do it."
      - "Don't be shy! You can shoot at me next time, I don't mind!"
      - "You must be new at this!"
      - "Is that really a gun in your hand or is it just wishful thinkin'!"