# MVPJoinAlert config.yml
# Copyright 2020, Jericho Crosby, <jericho.crosby227@gmail.com>

JoinMessage:
  default:
    enabled: false
    permission: "none"
    message:
      - "&6%name% &8joined the server!"
  VIP:
    permission: "mvp.vip"
    message:
      - "&8[&3MVP&8] &2%name% joined the server!"