name: MVPJoinAlerts
version: '${project.version}'
main: com.jericho.Main
api-version: 1.19
authors: [ Jericho ]
description: Broadcast a special message when an MVP joins
commands:
  mvp_reload:
    description: Reload the plugin
    permission: mvp.reload
    usage: /mvp_reload
    permission-message: "&cYou do not have permission to use this command!"