settings:

  #Valid Actions are kick or ban
  default-action: 'kick'

  reason: 'Duplicate IP'

  # Players with these IP addresses will not be auto-kicked.
  whitelist:
    - '127.0.0.1'
    - '127.0.0.1'
    - '127.0.0.1'